### ISSUE TITLE
Document process for adding a new network to Ops - checklist

### ISSUE THREAD

**Issue by Matthews3301** [gelatodigital/ops#54]
### Smart contract

- [ ]  Deploy IceCreamNFT
- [ ]  Deploy Forwarder
- [ ]  Deploy TaskTreasuryL2
- [ ]  Deploy TaskTreasuryUpgradable
- [ ]  Deploy Ops.sol
- [ ]  Whitelist Ops on TaskTreasuryUpgradable
- [ ]  Whitelist Ops on TaskTreasuryL2
- [ ]  Whitelist TaskTreasuryUpgradable on TaskTreasuryL2
- [ ] Add deployed addresses to /hardhat/config/addresses

### Subgraph

- [ ]  Add configs to subgraph
- [ ]  If network is a test net, add to `function isTestnet()`
- [ ]  If network is a prod net, add Uni v2 router, USD  and Wrapped native address
- [ ]  Add name and ticker for native token in `function getOrCreatePaymentToken()`
- [ ]  Deploy subgraph

### Backend

- [ ]  Add configs to backend
- [ ]  If network is a test net, add to `IS_TESTNET`
- [ ]  If network is a prod net, add wrapped native address
- [ ]  Deploy backend

**Comment by Matthews3301** [comment]
### Front-end (ops-interface)

- [ ] Update constants (`/src/constants/*`) to include:
  - supported chain data
  - new contract, query addresses
  - API addresses for chain id
  - other uses of chain id
  - wallet data (RPCs, native currency, etc.)
  - network selection dropdown data - color, index, name
  - network token
- [ ] Update `/src/connectors`
- [ ] Create block explorer account (e.g. Bscscan) - update `.env` file and Vercel with API key
- [ ] Make sure all functions formatting block explorer url now include new chainId - `addEtherscan`, `getEtherscanApiLink`, `getExplorerLink`, `getExplorerLinkForTx`, `getExplorerLinkForAddress`
- [ ] If new chain is a mainnet - add an icon to the front-page
- [ ] Update function retrieving token price from CoinGecko - `getTokenUSDPriceGecko`
- [ ] Verify that tutorial task can be created, it executes and the logs are showing up

### Notification system (gel-watcher)
- [ ] Update `/src/constants/networks` to include new chain data
